sudo: required
language: go
go:
- 1.12.x
env:
- GO111MODULE=on
services:
- docker
script:
- docker build -t centeredge/shawarma-webhook:${TRAVIS_BUILD_NUMBER} --build-arg VERSION=${TRAVIS_TAG:-0.0.0} .
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/docker_push.sh
  on:
    tags: true
